name: Security Scan
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Security Scan
        run: echo "TODO: Add security scan command here"
